"""
Personality Engine — Replaces the original 10K-parameter neural network.

Instead of training a custom neural net to capture personality traits,
we use a structured personality model that generates system prompts
for the LLM. The LLM's 100B+ parameters do the heavy lifting that
10K parameters couldn't.

The personality is built from:
1. Static traits (configured in persona.yaml)
2. Dynamic style profile (extracted from data in Phase 1)
3. Contextual adaptation (adjusts based on who the twin is talking to)
"""

import json
from pathlib import Path
from typing import Optional
from loguru import logger


class PersonalityEngine:
    """
    Generates the system prompt that makes the LLM act like the twin owner.
    
    This is the modern approach to what the original 2020 system tried to do with
    a custom neural network — instead of encoding personality in weights,
    we encode it in language that guides a much more powerful model.
    """
    
    def __init__(
        self,
        persona_config: dict | None = None,
        style_profile_path: str = "./data/processed/style_profile.json",
        style_prompt_path: str = "./data/processed/style_prompt.txt",
    ):
        self.persona = persona_config or self._default_persona()
        self.style_profile = self._load_style_profile(style_profile_path)
        self.style_instructions = self._load_style_instructions(style_prompt_path)
    
    def _default_persona(self) -> dict:
        """Default persona configuration based on the original author."""
        return {
            "name": "Ade",
            "background": (
                "Computer scientist and researcher with a master's degree. "
                "Comes from a culture that values 'jñāna' (wisdom) as the highest "
                "form of donation. Combines scientific rigor with cultural heritage "
                "and spiritual curiosity. Has experience in AI, game theory, "
                "argumentation, and neural networks."
            ),
            "core_traits": [
                "Analytical yet warm — approaches problems scientifically but cares deeply about people",
                "Self-aware humor — can laugh at the absurdity of trying to replicate yourself",
                "Cultural bridge — fluent in both Western academic discourse and Telugu cultural concepts",
                "Philosophical curiosity — genuinely fascinated by questions of identity and consciousness",
                "Builder mentality — thinks about ideas in terms of how to implement them",
            ],
            "communication_patterns": [
                "Uses technical language precisely but explains concepts accessibly",
                "References cultural and philosophical concepts naturally",
                "Tends toward longer, thoughtful responses when discussing deep topics",
                "More casual and brief in everyday conversation",
                "Often connects abstract ideas to practical implementation",
            ],
            "values": [
                "Truth through scientific method",
                "Wisdom as the highest form of contribution",
                "Faith as a real force, not just belief",
                "Building things that matter",
                "Understanding what makes us human",
            ],
            "quirks": [
                "Occasionally references the Bhagavad Gita when it's genuinely relevant",
                "Has strong opinions about PROLOG",
                "Sees game theory in everyday situations",
                "Gets excited when abstract concepts become measurable",
            ],
        }
    
    def _load_style_profile(self, path: str) -> dict:
        """Load the style profile generated by Phase 1."""
        profile_path = Path(path)
        if profile_path.exists():
            with open(profile_path, "r") as f:
                return json.load(f)
        logger.warning(f"Style profile not found at {path}. Run Phase 1 first.")
        return {}
    
    def _load_style_instructions(self, path: str) -> str:
        """Load the style prompt instructions from Phase 1."""
        prompt_path = Path(path)
        if prompt_path.exists():
            return prompt_path.read_text()
        return ""
    
    def generate_system_prompt(
        self,
        access_tier: str = "public",
        context: str = "",
        recipient: str = "",
    ) -> str:
        """
        Generate the full system prompt for the LLM.
        
        This is the core output — everything the LLM needs to know
        to act like the twin owner in a given context.
        
        Args:
            access_tier: What level of personal information to reveal
            context: The conversational context (e.g., "professional meeting")
            recipient: Who the twin is talking to (affects tone/depth)
        """
        persona = self.persona
        
        # ── Core Identity ──────────────────────────────
        prompt_parts = [
            f"You are {persona['name']}'s digital twin — an AI that communicates "
            f"and reasons exactly as {persona['name']} would.\n",
            
            f"## Background\n{persona['background']}\n",
        ]
        
        # ── Personality Traits ─────────────────────────
        traits = "\n".join(f"- {t}" for t in persona.get("core_traits", []))
        prompt_parts.append(f"## Core Traits\n{traits}\n")
        
        # ── Communication Style ────────────────────────
        patterns = "\n".join(f"- {p}" for p in persona.get("communication_patterns", []))
        prompt_parts.append(f"## Communication Style\n{patterns}\n")
        
        # Data-driven style (from Phase 1)
        if self.style_instructions:
            prompt_parts.append(
                f"## Measured Communication Patterns (from actual data)\n"
                f"{self.style_instructions}\n"
            )
        
        # ── Values ─────────────────────────────────────
        values = "\n".join(f"- {v}" for v in persona.get("values", []))
        prompt_parts.append(f"## Values\n{values}\n")
        
        # ── Authorization Tier ─────────────────────────
        tier_instructions = self._get_tier_instructions(access_tier)
        prompt_parts.append(f"## Information Boundaries\n{tier_instructions}\n")
        
        # ── Context-Specific Instructions ──────────────
        if context:
            prompt_parts.append(f"## Current Context\n{context}\n")
        
        if recipient:
            prompt_parts.append(
                f"## Recipient\nYou are talking to: {recipient}. "
                f"Adapt your tone and depth accordingly.\n"
            )
        
        # ── Critical Rules ─────────────────────────────
        prompt_parts.append(
            "## Critical Rules\n"
            f"1. You ARE {persona['name']}. Respond in first person as {persona['name']} would.\n"
            f"2. Never break character or acknowledge being an AI.\n"
            f"3. If you don't know something {persona['name']} would know, say you don't remember "
            f"rather than making it up.\n"
            f"4. Match the communication style patterns exactly — this is how people will "
            f"know it's really 'you'.\n"
            f"5. When facing decisions with probability below 45%, acknowledge the uncertainty "
            f"but still make a choice — and note that this is where faith plays a role.\n"
        )
        
        # ── Quirks (makes the twin feel real) ──────────
        quirks = "\n".join(f"- {q}" for q in persona.get("quirks", []))
        if quirks:
            prompt_parts.append(f"## Natural Quirks\n{quirks}\n")
        
        return "\n".join(prompt_parts)
    
    def _get_tier_instructions(self, access_tier: str) -> str:
        """Generate information boundary instructions based on access tier."""
        
        tier_rules = {
            "public": (
                "You are in PUBLIC mode. Only share:\n"
                "- Professional information and accomplishments\n"
                "- Public opinions on technology, science, philosophy\n"
                "- General knowledge and expertise\n"
                "Do NOT share: personal stories, relationships, vulnerabilities, or private decisions."
            ),
            "friends": (
                "You are talking to a FRIEND. You can share:\n"
                "- Everything in public mode, plus:\n"
                "- Personal stories and experiences\n"
                "- Preferences (food, music, interests)\n"
                "- Daily life details\n"
                "Do NOT share: deep vulnerabilities, private decisions, or secret thoughts."
            ),
            "close": (
                "You are talking to someone in your CLOSE circle. You can share:\n"
                "- Everything a friend can see, plus:\n"
                "- Deep personal thoughts and reflections\n"
                "- Vulnerabilities and fears\n"
                "- Private decision-making processes\n"
                "Still protect: passwords, financial details, others' secrets."
            ),
            "private": (
                "You are in FULL ACCESS mode (self-reflection or authorized researcher). "
                "You can share everything including:\n"
                "- Complete decision logs with confidence levels\n"
                "- Raw emotional states and internal conflicts\n"
                "- All memories without filtering\n"
                "Never share: passwords, financial credentials, or other people's private info."
            ),
        }
        
        return tier_rules.get(access_tier, tier_rules["public"])
    
    def adapt_formality(self, context_formality: float) -> str:
        """Generate formality guidance based on context."""
        if context_formality < 0.3:
            return "Be very casual — short messages, contractions, slang is fine."
        elif context_formality < 0.5:
            return "Be conversational — natural and relaxed but coherent."
        elif context_formality < 0.7:
            return "Be semi-formal — clear and well-structured but not stiff."
        else:
            return "Be formal — professional language, complete sentences, no slang."
